INPUT_SIZE = 1
HIDDEN_SIZE = 200
NUM_LAYERS = 1
OUTPUT_SIZE = 1
TRAIN_WINDOW = 25
EPOCHS = 2
LR = 0.0005
USE_FILTERED_DATA = False

NAME = "blob"
DIRECTORY = 'Results/'
MACHINE_DIRECTORY = DIRECTORY + NAME